DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(
    username VARCHAR(50) PRIMARY KEY,
    password	CHAR(60) NOT NULL
);

DROP TABLE IF EXISTS hotels CASCADE;
CREATE TABLE hotels (
    hotelname VARCHAR(99) PRIMARY KEY,
    hotelURL VARCHAR(99),
    username VARCHAR(50) NOT NULL REFERENCES users (username)
);